/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_titech_cs_de_ykstorage_storage_datadisk_NormalDataDiskManager */

#ifndef _Included_jp_ac_titech_cs_de_ykstorage_storage_datadisk_NormalDataDiskManager
#define _Included_jp_ac_titech_cs_de_ykstorage_storage_datadisk_NormalDataDiskManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_ac_titech_cs_de_ykstorage_storage_datadisk_NormalDataDiskManager
 * Method:    write
 * Signature: (Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_titech_cs_de_ykstorage_storage_datadisk_NormalDataDiskManager_write
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     jp_ac_titech_cs_de_ykstorage_storage_datadisk_NormalDataDiskManager
 * Method:    read
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jp_ac_titech_cs_de_ykstorage_storage_datadisk_NormalDataDiskManager_read
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
