package jp.ac.titech.cs.de.ykstorage.cli;

public class InputClientException extends RuntimeException {
	
	/** This value is generated by Eclipse IDE. */
	private static final long serialVersionUID = 7829963753308868423L;

	public InputClientException() {
		super();
	}
	
	public InputClientException(String message) {
		super(message);
	}
}
